### ISSUE TITLE
Check how measure numbers in annot tool tips are retrieved, there seems to be something wrong…

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#281] opened 2022-09-23 16:05 UTC
<img width="543" alt="Bildschirmfoto 2022-09-23 um 18 04 14" src="https://user-images.githubusercontent.com/2676362/192004275-a047579a-71ee-42f3-be30-f44b034c7fdf.png">

**Comment by nikobeer** [comment] 2022-09-23 16:08
@n, @label or what…?

**Comment by bwbohl** [comment] 2022-10-05 13:06
could you please describe what you were expecting in the above example, both visually and in terms of encoding, and maybe provide encoding examples?

**Comment by bwbohl** [comment] 2022-10-05 13:06
As you self-assigned: will you fix this by yourself or do you need some help?

**Comment by nikobeer** [comment] 2022-10-05 13:23
Yes, I will fix it – at the end of October/beginning November. There is probably a special xquery for these tooltips that is not aware of some "logic modifications" we made to the full Annotation View xquery in the past.

**Comment by nikobeer** [comment] 2022-11-23 11:03
Starting at getAnnotations.xql…

**Comment by roewenstrunk** [comment] 2022-12-14 13:18
The problem is not supported @label in line https://github.com/Edirom/Edirom-Online/blob/ea4c7c3479b8cc62569a8cb5c247c5447456fb89/add/data/xql/getAnnotation.xql#L208

**Comment by krHERO** [comment] 2024-05-30 07:43
@nikobeer what is the status of this issue?

**Comment by nikobeer** [comment] 2024-06-04 09:20
This Problem is not solved yet.

**Comment by nikobeer** [comment] 2024-06-04 10:05
Fixed. @bwbohl please close when pulled…

**Comment by bwbohl** [comment] 2024-06-04 10:26
am I right to assume that the to above commits in the MRI Edirom Online are the fix for this issue?

**Comment by nikobeer** [comment] 2024-06-04 10:30
The first (fe4ed58) is in the MRI's repo. It is only valid for the RWA Edirom as getAnnotation.xql there looks completely different from the original Edirom file. The second ([a55a0f5](https://github.com/Edirom/Edirom-Online/commit/a55a0f555509f4ffffe4169222a1259724aad80b)) is the actual fix for Edirom (same code change). See https://github.com/Edirom/Edirom-Online/pull/380.

**Comment by bwbohl** [comment] 2024-06-04 10:34
thx for clarifying, oversay the corresponding PR. I now linked the issue and the PR from the Development section in the righthand siedebar

**Closed** 2024-06-19 08:13 UTC
Labels: Type: inconsistency report
