### ISSUE TITLE
Installation instructions for installing Edirom-Online as-a-service on Linux

### ISSUE THREAD

**Issue by Herrner** [Edirom/Edirom-Online#106] opened 2017-03-21 14:39 UTC
Is anyone working on installation instructions for Edirom-Online (as a service) on Linux? 
I'm failing miserably at the task of installing components using the instructions for OSX, and would really like something like that for Linux. Or are there any other instructions I just haven't found yet?

**Comment by bwbohl** [comment] 2017-03-21 16:03
Not at the moment I think, but several people should have successfully setup Edirom-Online on Linux servers. What are the steps you're failing on?

**Comment by Herrner** [comment] 2017-03-30 08:43
Oh, my failures are manyfold... I succeeded installing eXist, Jetty, DigiLib and - I guess - SenchaCmd. I can't really try, since I figured that I first need to prepare content through the Edirom Editor before I can test my installation and now I'm not getting that to work (I actually cannot find the "Edirom Server" anywhere. 
I'll probably just quit on that whole enterprise, since I really cannot recommend that kind of workflow to anyone else - so maybe just ignore the issue.

**Comment by bwbohl** [comment] 2017-04-03 14:58
Well Edirom Editor itself is outdated and requires older Java versions to work Where did you read about "Edirom Server" because that really is not what you need?
There's much work going on at the moment implementing new tools or investigating in using Docker to setup Edirom. BTW there's a test data set under construction at https://github.com/Edirom/EditionExample

**Comment by bwbohl** [comment] 2017-04-03 15:00
Edirom Editor needs a 32-bit Java 6 or 7 installed but I never tested on Linux, only Windows or OS X.

**Comment by bwbohl** [comment] 2017-04-03 15:02
maybe @nikobeer can help, he has set up Edirom Online, Jetty/digilib on Linux

**Comment by Herrner** [comment] 2017-04-05 12:08
I guess I'll try to go with the Edition Example, but since ît's not really obvious how to create content for Eirom Online now, I think we'll refrain form using ediroam at all.
For me, the trouble starts [here](https://github.com/Edirom/Edirom-Online/wiki/Preparing-your-content-for-Edirom-Online) (link to "current version" is dead), the link to edirom.de -> tools just brings me back here, and http://www.edirom.de/edirom-projekt/software/edirom-werkzeuge/ mentions the unfindable edirom-server.

**Comment by bwbohl** [comment] 2017-04-05 12:49
thans for pointing to the dead links!!
Get Edirom Editor from https://github.com/Edirom/Edirom-Editor/releases and see system requirements at https://github.com/Edirom/Edirom-Editor/
The whole ["edirom-projekt"]( http://www.edirom.de/edirom-projekt/) subtree of http://www.edirom.de/ is online for archival purposes and is not being updated anymore, unfortunately this makes deprecated information available, sorry for that inconvenience…

If you get it up and running use _Edirom Editor_ for a first step. You can come back to me if you need support. If you have some basic content set up you . have to Export it for _Edirom Online_ and deploy it in eXist-db

**Comment by amadeusgwin** [comment] 2017-05-30 11:15
Hi, I will take over at this point trying to get Edirom Online running. Since the Edirom Editor requires some deprecated resources, would it be possible to deploy a (minimal) sample xml-file that one could use to upload into the /db/contents/ folder in the exist collections, that is then to be specified as paths in the js-files in order to build finally the Edirom Online xar-file? In other words, which content should the described edition-MyEdition.xml have? I just need a correct xml-file to test if everything is working fine with our installation.

**Comment by amadeusgwin** [comment] 2017-05-31 07:52
If I take the EditionExample from above (which is probably incomplete) and adjust the configuration files (Application.js, ImageViewer.js, and edirom-prefs.xml (after copying the relevant files to the collections of the exist DB), the build script will issue the following error
[ERR] The following error occurred while executing this line:
/home/user/Edirom-Online/.sencha/app/build-impl.xml:273: The following error occurred while executing this line:
/home/user/Edirom-Online/.sencha/app/sass-impl.xml:127: The following error occurred while executing this line:
/home/user/Edirom-Online/.sencha/app/sass-impl.xml:138: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
I checked the respective lines, but could not find any inconsistencies. Does anyone have an idea what the cause of the error could be?

**Comment by amadeusgwin** [comment] 2017-05-31 07:53
I am using Sencha Cmd v6.2.1.29

**Comment by nikobeer** [comment] 2017-05-31 08:24
Hi and thanks for your comments here! We are currently busy finalizing new Edirom Online version/release. I'll come back to you in the next week. From which branch did you check out the code?

As I understand, jetty, digilib and eXist-db are running? The remaining problem is building the Edirom Online app package?

**Comment by amadeusgwin** [comment] 2017-05-31 08:43
So it is! jetty, digilin, eXist are up and running. We checked out from the master branch. And yes, it seems as though the Edirom Online app package is not build correctly.

**Comment by bwbohl** [comment] 2017-06-06 12:53
Hi @amadeusgwin just seen your question today returning from a week of…

Could you please try building from the develop branch for a first try? Been building from there just a few weeks ago.
Nevertheless @nikobeer might come back to you with a better codebase.

**Comment by amadeusgwin** [comment] 2017-06-12 09:50
Hi @bwbohl thanks for taking up this issue again: also from the development branch, the exact same errors as above are output. So best I try @nilobeer codebase next.

**Comment by amadeusgwin** [comment] 2017-06-28 11:26
Hi @bwbohl thanks for taking up this issue again: also from the development branch, the exact same errors as above are output. So best I try @nilobeer codebase next.

**Comment by amadeusgwin** [comment] 2017-06-28 11:28
Hi @nikobeer, is there some other codebase that I could try out yet or in the near future?

**Comment by bwbohl** [comment] 2022-02-01 22:55
as deployment of edirom strongly makes use of docker containers today, I close this issue.

**Closed by bwbohl** 2022-02-01 22:55 UTC
Labels: documentation, Type: support request
